version: '3.8'

networks:
  network-label:
    name: task2-network
    driver: bridge

services:

  # Master for delegate heavy work to worker containers
  jobmanager-label:
    networks:
      - network-label
    build:
      context: .
      args:
        - FLINK_VERSION=${FLINK_VERSION}
    container_name: task2-jobmanager
    ports:
      - "${FLINK_PORT}:${FLINK_PORT}"
    # start up in master mode  
    command: jobmanager
    volumes:
      - ./.env:/opt/flink/.env
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager-label


  # Flink TaskManager - worker for computations
  taskmanager-label:
    networks:
      - network-label
    build:
      context: .
      args:
        - FLINK_VERSION=${FLINK_VERSION}
    container_name: task2-taskmanager
    depends_on:
      - jobmanager-label
    command: taskmanager
    volumes:
      - ./.env:/opt/flink/.env
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager-label
        taskmanager.numberOfTaskSlots: ${FLINK_TASK_SLOTS}

  # Kafka Services

    # KRaft Kafka Broker
  kafka-label:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    networks:
      - network-label
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-label:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:${KAFKA_PORT}'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-label:9092,PLAINTEXT_HOST://localhost:${KAFKA_PORT}'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'


  # Kafka Web UI
  kafka-ui-label:
    image: kafbat/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "${KAFKA_UI_PORT}:${KAFKA_UI_PORT}"
    networks:
      - network-label
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kraft-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-label:9092

  # InfluxDB time-series storage
  influxdb-label:
    image: influxdb:2.7
    container_name: task2-influxdb
    ports:
      - "8087:8086"
    networks:
      - network-label
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}